let personnelTransferColumns = [{
  "prop": "operate",
  "label": "操作",
  "width": 180
}, {
  "prop": "psnNo",
  "label": "人员编号",
  "width": 120
}, {
  "prop": "psnName",
  "label": "人员姓名",
  "width": 80
}, {
  "prop": "insutype",
  "label": "险种类型",
  "width": 80
}, {
  "prop": "insuOptins",
  "label": "参保机构医保区划",
  "width": 150
}, {
  "prop": "diagCode",
  "label": "诊断代码",
  "width": 80
}, {
  "prop": "diagName",
  "label": "诊断名称",
  "width": 80
}, {
  "prop": "tel",
  "label": "联系电话",
  "width": 80
}, {
  "prop": "addr",
  "label": "联系地址",
  "width": 80
}, {
  "prop": "diseCondDscr",
  "label": "疾病病情描述",
  "width": 120
}, {
  "prop": "reflinMedinsNo",
  "label": "转往定点医药机构编号",
  "width": 170
}, {
  "prop": "reflinMedinsName",
  "label": "转往医院名称",
  "width": 120
}, {
  "prop": "mdtrtareaAdmdvs",
  "label": "就医地行政区划",
  "width": 120
}, {
  "prop": "hospAgreReflFlag",
  "label": "医院同意转院标志",
  "width": 140
}, {
  "prop": "reflType",
  "label": "转院类型",
  "width": 80
}, {
  "prop": "reflDatetime",
  "label": "转院日期",
  "width": 80
}, {
  "prop": "reflRea",
  "label": "转院原因",
  "width": 80
}, {
  "prop": "reflOpnn",
  "label": "转院意见",
  "width": 80
}, {
  "prop": "begndatetime",
  "label": "开始日期",
  "width": 80
}, {
  "prop": "enddatetime",
  "label": "结束日期",
  "width": 80
}];
let formList = [{
  "span": 6,
  "type": "input",
  "label": "人员编号",
  "prop": "psnNo",
  "required": true,
  "disabled": true
}, {
  "span": 6,
  "type": "input",
  "label": "人员姓名",
  "prop": "psnName",
  "required": true,
  "disabled": true
}, {
  "span": 6,
  "type": "select",
  "label": "险种类型",
  "prop": "insutype",
  "name": "insutypeName",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "select",
  "label": "参保机构医保区划",
  "prop": "insuOptins",
  "name": "insuOptinsName",
  "required": true,
  "disabled": true
}, {
  "span": 6,
  "type": "select",
  "label": "诊断",
  "prop": "diagCode",
  "name": "diagName",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "input",
  "label": "联系电话",
  "prop": "tel",
  "required": true,
  "disabled": false
}, {
  "span": 12,
  "type": "input",
  "label": "联系地址",
  "prop": "addr",
  "required": true,
  "disabled": false
}, {
  "span": 24,
  "type": "textArea",
  "label": "疾病病情描述",
  "prop": "diseCondDscr",
  "required": true,
  "disabled": false,
  maxlength: 1000,
  minRows: 1
}, {
  "span": 6,
  "type": "select",
  "label": "定点医药机构类型",
  "prop": "fixmedinsType",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "select",
  "label": "转往医院名称",
  "prop": "reflinMedinsNo",
  "name": "reflinMedinsName",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "input",
  "label": "转往定点医药机构编号",
  "prop": "reflinMedinsNoInit",
  "required": true,
  "disabled": true
}, {
  "span": 6,
  "type": "select",
  "label": "就医地行政区划",
  "prop": "mdtrtareaAdmdvs",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "select",
  "label": "医院同意转院标志",
  "prop": "hospAgreReflFlag",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "select",
  "label": "转院类型",
  "prop": "reflType",
  "required": true,
  "disabled": false
}, {
  "span": 6,
  "type": "date",
  "label": "转院日期",
  "prop": "reflDatetime",
  "required": true,
  "disabled": false
}, {
  "span": 24,
  "type": "textArea",
  "label": "转院原因",
  "prop": "reflRea",
  "required": true,
  "disabled": false,
  maxlength: 1000,
  minRows: 1
}, {
  "span": 24,
  "type": "textArea",
  "label": "转院意见",
  "prop": "reflOpnn",
  "required": true,
  "disabled": false,
  maxlength: 1000,
  minRows: 1
}, {
  "span": 12,
  "type": "date",
  "label": "开始日期",
  "prop": "begndatetime",
  "required": true,
  "disabled": false
}, {
  "span": 12,
  "type": "date",
  "label": "结束日期",
  "prop": "enddatetime",
  "required": true,
  "disabled": false
}];
let rules = {
  psnNo: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  psnName: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  diagCode: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }],
  tel: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  addr: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  diseCondDscr: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  reflinMedinsNo: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  reflinMedinsName: [{
    required: true,
    message: '请输入',
    trigger: 'blur'
  }],
  mdtrtareaAdmdvs: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }],
  reflType: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }],
  reflDatetime: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }],
  reflRea: [{
    required: true,
    message: '请输入',
    trigger: 'blue'
  }],
  reflOpnn: [{
    required: true,
    message: '请输入',
    trigger: 'blue'
  }],
  begndatetime: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }],
  enddatetime: [{
    required: true,
    message: '请输入',
    trigger: 'change'
  }]
};

export {
  personnelTransferColumns,
  formList,
  rules
}
